config/routes.rb
Rails.application.routes.draw do

  resources :games, only: [:new, :create, :show] do
    member do
      post :add_boat
      post '/guess' => 'games#guess'
    end
    collection do
      post :difficulty
    end
  end

  root 'games#new'
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :boards, autosave: true
  before_create :create_boards

  def create_boards
    boards.new(owner: 'Computer')
    boards.new(owner: 'Human')
  end

  def winner
    human_boats_remaining = boards.find_by(owner: 'Human').spaces.boats.count
    computer_boats_remaining = boards.find_by(owner: 'Computer').spaces.boats.count
    return 'Tie' if human_boats_remaining + computer_boats_remaining == 0
    return 'Human' if computer_boats_remaining == 0
    return 'Computer' if human_boats_remaining == 0
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :find_game

  def new
  end

  def create
    @game = Game.create
    redirect_to @game
  end

  def show
    @game = Game.find(params[:id])
    spaces_count = @game.boards.map { |a| a.spaces.count }.inject(:+)
    if @game.winner
      @winner = @game.winner
      render 'winner' and return
    end
    if spaces_count # >= Boat.pluck(:size).map(&:to_i).inject(:+) * 2
     render 'show'
    else
     render 'setup'
    end
  end

  def guess
    computer_board_guess = computer_board.guess(*Coords.new(params[:guess]))
    if !computer_board_guess[:state].in? ['invalid guess', 'already guessed']
      guess = Guesser.new(human_board.spaces, session[:difficulty]).run!
      human_board_guess = human_board.guess(*guess)
    else
      human_board_guess = {}
    end
    respond_to do |format|
      format.html { redirect_to @game }
      format.json do
        json = { computer_board: computer_board_guess, human_board: human_board_guess }
        render json: json
      end
    end
  end

  def add_boat
    @game = Game.find(params[:id])
    boat = Boat.find_by name: params[:boat_name]
    board = @game.boards.find_by owner: 'Human'
    if board.create_spaces_for_boat boat, params[:letter] + params[:number], 'right'
      redirect_to @game
    else
      redirect_to @game, flash: 'Something went wrong'
    end
  end

  def difficulty
    session[:difficulty] = params[:difficulty].to_i
    render nothing: true
  end


  private

  def find_game
    @game = Game.find(params[:id]) if params[:id]
  end

  def computer_board
    @computer_board ||= @game.boards.detect { |a| a.owner == 'Computer' }
  end

  def human_board
    @human_board ||= @game.boards.detect { |a| a.owner == 'Human' }
  end

end

app/views/games/_start.html.haml
= form_tag difficulty_games_path, method: :post, remote: true do

  .form-group
    = radio_button_tag :difficulty, 1, session[:difficulty] == 1
    = label_tag :difficulty_1, 'Easy'

  .form-group
    = radio_button_tag :difficulty, 2, session[:difficulty] == 2
    = label_tag :difficulty_2, 'Medium'

  .form-group
    = radio_button_tag :difficulty, 3, session[:difficulty] == 3
    = label_tag :difficulty_3, 'Hard'

  .form-group
    = radio_button_tag :difficulty, 4, session[:difficulty] == 4
    = label_tag :difficulty_4, 'Impossible'


= button_to 'Start Game', games_path, class: 'btn btn-success'

app/views/games/new.html.haml
%h1.big-welcome BATTLESHIP

= render 'start'

app/views/games/setup.html.haml
- board = @game.boards.find_by(owner: 'Human')
.setup
  .row-fluid
    .col-md-6
      %table.grid
        - Board.unflat_grid.each do |row|
          %tr
            - row.each do |space|
              %td.space{class: ('boat' if space.in?(board.current_occupied_spaces))}= space.join ''

    .col-md-6
      %h3 Boats
      %ul
        - Boat.all.each do |boat|
          %li.setup-boat{data: { size: boat.size, name: boat.name }} #{boat.name}: #{boat.size}

app/views/games/show.html.haml
- computer_board = @game.boards.find_by(owner: 'Computer')
- human_board = @game.boards.find_by owner: 'Human'
.show
  .row-fluid
    .col-lg-6.col-sm-12
      %h1 Computer
      %table.grid.computer
        - Board.unflat_grid.each do |row|
          %tr
            - row.each do |spaceArray|
              - space = spaceArray.join('')
              -# html_class = 'boat' if space.in?(computer_board.current_occupied_spaces)
              - html_class = 'hit' if space.in?(computer_board.hit_spaces)
              - html_class = 'guessed' if space.in? computer_board.guessed_spaces
              %td.space{class: html_class, data: { letter: spaceArray[0], number: spaceArray[1].to_s }}
                %button.btn.space
                  - guess = space
                  = link_to guess, guess_game_path(@game, guess: guess), class: 'fire', method: :post

    .col-lg-6.col-sm-12
      %h1 YOUR BOARD
      %table.grid.human
        - Board.unflat_grid.each do |row|
          %tr
            - row.each do |spaceArray|
              - space = spaceArray.join ''
              - html_class = 'boat' if space.in?(human_board.current_occupied_spaces)
              - html_class = 'hit' if space.in?(human_board.hit_spaces)
              - html_class = 'guessed' if space.in? human_board.guessed_spaces
              %td.space{class: html_class, data: { letter: spaceArray[0], number: spaceArray[1] }}
                %button.btn.space
                  = space

app/views/games/winner.html.haml
%h1
  - if @winner == 'Tie'
    It's a TIE
  - else
    #{@winner} WINS

= render 'start'